### PR TITLE
Pass relative path from config directory to 'flow autocomplete'

### PR DESCRIPTION
**Pull request by minodisk**
autocomplete-flow didn't complete `require`d implementations. The reason was that the relative path of the file was not passed to `flow autocomplete`.

Some codes are borrowed from https://github.com/steelsojka/deoplete-flow/pull/9 .

### CODE REVIEW

**Comment by wokalski** [comment]
@minodisk one question, what's the advantage of this plugin over `deoplete-flow`? Otherwise, it's good to merge.

**Comment by minodisk** [comment]
@wokalski I think there are several pros.

- Finds local `flow-bin` automatically: https://github.com/wokalski/autocomplete-flow/blob/f7c4bca879bd83a86b15002a62cb5ee748d122c4/plugin/deoplete-flow.vim#L8-L13
- Starts flow server automatically: https://github.com/steelsojka/deoplete-flow/issues/8
- PRs are merged: https://github.com/wokalski/autocomplete-flow/pulls?q=is%3Apr+is%3Aclosed

I think that enough implementation is done to use it. Thanks for your work 🍣

**Comment by wokalski** [comment]
@minodisk doesn't it work super slow for you? Last time I used it I had some issues with it but I couldn't figure out why it started suddenly behaving that way.

**Comment by minodisk** [comment]
@wokalski For now, it works fast and doesn't behave slow down in my environment.

**Pull request merged**
